Созданы моки и отрисованы по шаблонам
htmlacademy-ecmascript/647095-big-trip-12 pull request #5
Opened 2020-09-05 17:32 UTC by Renzi0n

2020-09-06 18:28 UTC, balesniy requested changes
все хорошо получилось, осталось немного поправить структуру моковых данных :+1:

2020-09-06 18:28 UTC, balesniy commented on src/view/tripDay.js
> +  const isEventEdit = getRandomBooleanValue(); // Выбираем случайно будет ли в дне форма редактирования
нам нужно отрисовать только одну форму на странице, для первого события, логику выбора шаблона имеет смысл оставить в main. хотя для этого задания не принципиально)

2020-09-06 18:28 UTC, balesniy commented on src/mock/event.js
> +  let photos = [];
const

2020-09-06 18:28 UTC, balesniy commented on src/mock/event.js
> +  for (let i = 0; i < getRandomInteger(1, MAX_DESCRIPTIONS); i++) {
выбор случайного количества элементов нужно вынести из цикла, иначе число меняется на каждой итерации

2020-09-06 18:28 UTC, balesniy commented on src/mock/event.js
> +  return new Date(currentDate);
currentDate объявлен объектом даты, второй раз передавать его в конструктор избыточно

2020-09-06 18:28 UTC, balesniy commented on src/mock/event.js
> +    placeInfo: generatePlaceInfo(),
информацию о месте назначения нужно привязать к city, чтобы у разных точек в одном городе было одинаковое описание

2020-09-06 18:28 UTC, balesniy commented on src/mock/event.js
> +  const timeOver = new Date(new Date(date).setTime(getRandomInteger(date.getTime(), date.getTime() + 24 * 360 * 1000)));
лишний второй конструктор new Date

2020-09-06 18:28 UTC, balesniy commented on src/mock/event.js
> +    return offersForEvent[it];
объекты передаются по ссылке и так они  разделяются между событиями, можно скопировать их из справочника offersForEvent с помощью Object.assign чтобы у отдельных событий появились независимые поля check

2020-09-06 18:28 UTC, balesniy commented on src/view/event.js
> +  return hours + minInHour;
мы уже знаем про шаблонные строки, конкатенацию можно не использовать

2020-09-06 18:28 UTC, balesniy commented on src/view/event.js
> +          ${createEventOffersTemplate(offers)}
количество отображаемых в таблице опций нужно ограничить 3 и выводить только выбранные пользователем

2020-09-07 00:26 UTC, Renzi0n commented on src/mock/event.js
> +  const timeOver = new Date(new Date(date).setTime(getRandomInteger(date.getTime(), date.getTime() + 24 * 360 * 1000)));
Если я убираю один из конструкторов, то у меня во времени конца либо таймстэмп, либо такое же время как и в дате начала. Я если правильно понимаю метод setTime() возвращает таймпстэмп. Поэтому честно говоря я не знаю как можно улучшить эту запись

2020-09-07 07:14 UTC, balesniy commented on src/mock/event.js
> +  const timeOver = new Date(new Date(date).setTime(getRandomInteger(date.getTime(), date.getTime() + 24 * 360 * 1000)));
да, он возвращает таймпстэмп, но при этом меняет дату, так что у тебя остается ссылка на готовый объект даты

2020-09-07 16:58 UTC, merged